[build]
  command = "lerna bootstrap --hoist && lerna run build"

[context.production]
  publish = "packages/react-discovery-elasticsearch-app/build"

[context.production.environment]
  REACT_APP_SEARCH_API_COLLECTION = "hsp1"
  REACT_APP_SEARCH_API_HOST = "https://es.iiif.cloud/"

[context.deploy-preview]
  publish = "packages/react-discovery-elasticsearch-app/build"

[context.deploy-preview.environment]
  REACT_APP_SEARCH_API_COLLECTION = "hsp1"
  REACT_APP_SEARCH_API_HOST = "https://es.iiif.cloud/"

[context.solr]
    publish = "packages/react-discovery-solr-app/build"

[context.solr.environment]
  REACT_APP_SEARCH_API_COLLECTION = "test04"
  REACT_APP_SEARCH_API_HOST = "https://solr.iiif.cloud/"
