version: '3.7'
services:
  react-discovery-app:
    image: react-discovery-solr-app
    build: ../../packages/react-discovery-solr-app
    container_name: react-discovery-solr-app
    ports:
      - "5000:5000"
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - solr
    depends_on:
      - solr3
  solr1:
    container_name: solr1
    image: solr:8
    ports:
      - "8981:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    volumes:
      - ./solr-config/conf:/opt/solr-8.0.0/server/solr/configsets/_default/conf
      - ./solr-config/solr.in.sh:/etc/default/solr.in.sh
  solr2:
    image: solr:8
    container_name: solr2
    ports:
      - "8982:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    volumes:
      - ./solr-config/conf:/opt/solr-8.0.0/server/solr/configsets/_default/conf
      - ./solr-config/solr.in.sh:/etc/default/solr.in.sh
  solr3:
    image: solr:8
    container_name: solr3
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    ports:
      - 8983:8983
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    volumes:
      - ./solr-config/conf:/opt/solr-8.0.0/server/solr/configsets/_default/conf
      - ./solr-config/solr.in.sh:/etc/default/solr.in.sh
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr

networks:
  solr:
